// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/parser/tiktok/crypto/ttdevice/device.proto

package ttdevice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceInfo 是 TikTok native app /sdi/get_token 请求明文 field1 的设备详情 message。
//
// 字段定义由真机抓包样本(MI 6X / Android 9 / alisg-TW)的 protobuf wire 逆向而来,
// 逐字节对齐 605B 固定档。proto.Marshal 输出与原 hex 模板 IDENTICAL(已实测)。
// 原因:本 message 无任何字段等于 proto3 默认值(字符串占位用 "!notset!",整数占位
// 用 1999997),默认值省略规则不触发;protoc 按字段号升序写,与抓包顺序一致。
//
// 仅 install_uuid(field 26)为动态值,由 register 生成的 cdid 注入;其余字段为
// 固定设备档值。换设备档需重新抓包并更新本结构。
type DeviceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceBrand       string                 `protobuf:"bytes,1,opt,name=device_brand,json=deviceBrand,proto3" json:"device_brand,omitempty"`                    // "!notset!"
	Manufacturer      string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`                                     // "xiaomi"
	DeviceModel       string                 `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`                    // "MI 6X"
	DeviceName        string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`                       // "!notset!"
	OsName            string                 `protobuf:"bytes,5,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`                                   // "Android"
	OsVersion         string                 `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`                          // "9"
	ScreenResolution  string                 `protobuf:"bytes,7,opt,name=screen_resolution,json=screenResolution,proto3" json:"screen_resolution,omitempty"`     // "1080*2160"
	ScreenDpi         int64                  `protobuf:"varint,8,opt,name=screen_dpi,json=screenDpi,proto3" json:"screen_dpi,omitempty"`                         // 880
	RomBuildId        string                 `protobuf:"bytes,9,opt,name=rom_build_id,json=romBuildId,proto3" json:"rom_build_id,omitempty"`                     // "PKQ1.180904.001"
	Field10           int64                  `protobuf:"varint,10,opt,name=field10,proto3" json:"field10,omitempty"`                                             // 3115884974
	Locale            string                 `protobuf:"bytes,11,opt,name=locale,proto3" json:"locale,omitempty"`                                                // "zh_CN"
	Timezone          string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`                                            // "Asia/Shanghai,8"
	TzOffset          int64                  `protobuf:"varint,13,opt,name=tz_offset,json=tzOffset,proto3" json:"tz_offset,omitempty"`                           // 2748
	Field14           int64                  `protobuf:"varint,14,opt,name=field14,proto3" json:"field14,omitempty"`                                             // 200
	MemTotalBytes     int64                  `protobuf:"varint,15,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`          // 7842717696  (~7.3G RAM)
	StorageTotalA     int64                  `protobuf:"varint,16,opt,name=storage_total_a,json=storageTotalA,proto3" json:"storage_total_a,omitempty"`          // 108308496384
	StorageTotalB     int64                  `protobuf:"varint,17,opt,name=storage_total_b,json=storageTotalB,proto3" json:"storage_total_b,omitempty"`          // 108308496384
	StorageFree       int64                  `protobuf:"varint,18,opt,name=storage_free,json=storageFree,proto3" json:"storage_free,omitempty"`                  // 33828290560
	IdSlot_19         string                 `protobuf:"bytes,19,opt,name=id_slot_19,json=idSlot19,proto3" json:"id_slot_19,omitempty"`                          // "!notset!"(IMEI?)
	IdSlot_20         string                 `protobuf:"bytes,20,opt,name=id_slot_20,json=idSlot20,proto3" json:"id_slot_20,omitempty"`                          // "!notset!"(MAC?)
	IdSlot_21         string                 `protobuf:"bytes,21,opt,name=id_slot_21,json=idSlot21,proto3" json:"id_slot_21,omitempty"`                          // "!notset!"(serial?)
	IdSlot_22         string                 `protobuf:"bytes,22,opt,name=id_slot_22,json=idSlot22,proto3" json:"id_slot_22,omitempty"`                          // "!notset!"
	IdSlot_23         string                 `protobuf:"bytes,23,opt,name=id_slot_23,json=idSlot23,proto3" json:"id_slot_23,omitempty"`                          // "!notset!"
	DeviceFingerprint string                 `protobuf:"bytes,24,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"` // base64 哈希
	TimestampA        int64                  `protobuf:"varint,25,opt,name=timestamp_a,json=timestampA,proto3" json:"timestamp_a,omitempty"`                     // 3568087524
	InstallUuid       string                 `protobuf:"bytes,26,opt,name=install_uuid,json=installUuid,proto3" json:"install_uuid,omitempty"`                   // 动态:register 生成的 cdid
	DiskCapacity      int64                  `protobuf:"varint,27,opt,name=disk_capacity,json=diskCapacity,proto3" json:"disk_capacity,omitempty"`               // 743640924160
	Field28           string                 `protobuf:"bytes,28,opt,name=field28,proto3" json:"field28,omitempty"`                                              // "!notset!"
	Sentinel_29       int64                  `protobuf:"varint,29,opt,name=sentinel_29,json=sentinel29,proto3" json:"sentinel_29,omitempty"`                     // 1999997(占位)
	Sentinel_30       int64                  `protobuf:"varint,30,opt,name=sentinel_30,json=sentinel30,proto3" json:"sentinel_30,omitempty"`                     // 1999997
	Slot_31           string                 `protobuf:"bytes,31,opt,name=slot_31,json=slot31,proto3" json:"slot_31,omitempty"`                                  // "!notset!"
	Slot_32           string                 `protobuf:"bytes,32,opt,name=slot_32,json=slot32,proto3" json:"slot_32,omitempty"`                                  // "!notset!"
	Slot_33           string                 `protobuf:"bytes,33,opt,name=slot_33,json=slot33,proto3" json:"slot_33,omitempty"`                                  // "!notset!"
	Slot_34           string                 `protobuf:"bytes,34,opt,name=slot_34,json=slot34,proto3" json:"slot_34,omitempty"`                                  // "!notset!"
	Slot_35           string                 `protobuf:"bytes,35,opt,name=slot_35,json=slot35,proto3" json:"slot_35,omitempty"`                                  // "!notset!"
	Sentinel_36       int64                  `protobuf:"varint,36,opt,name=sentinel_36,json=sentinel36,proto3" json:"sentinel_36,omitempty"`                     // 1999997
	Sentinel_37       int64                  `protobuf:"varint,37,opt,name=sentinel_37,json=sentinel37,proto3" json:"sentinel_37,omitempty"`                     // 1999997
	Slot_38           string                 `protobuf:"bytes,38,opt,name=slot_38,json=slot38,proto3" json:"slot_38,omitempty"`                                  // "!notset!"
	Slot_39           string                 `protobuf:"bytes,39,opt,name=slot_39,json=slot39,proto3" json:"slot_39,omitempty"`                                  // "!notset!"
	NetIpList         string                 `protobuf:"bytes,40,opt,name=net_ip_list,json=netIpList,proto3" json:"net_ip_list,omitempty"`                       // '["10.0.0.1","0.0.0.0"]'
	Sentinel_41       int64                  `protobuf:"varint,41,opt,name=sentinel_41,json=sentinel41,proto3" json:"sentinel_41,omitempty"`                     // 1999997
	Sentinel_42       int64                  `protobuf:"varint,42,opt,name=sentinel_42,json=sentinel42,proto3" json:"sentinel_42,omitempty"`                     // 1999997
	Slot_44           string                 `protobuf:"bytes,44,opt,name=slot_44,json=slot44,proto3" json:"slot_44,omitempty"`                                  // "!notset!"
	Field45           int64                  `protobuf:"varint,45,opt,name=field45,proto3" json:"field45,omitempty"`                                             // 3419633858
	TimestampB        int64                  `protobuf:"varint,46,opt,name=timestamp_b,json=timestampB,proto3" json:"timestamp_b,omitempty"`                     // 3568087566
	ApkPath           string                 `protobuf:"bytes,47,opt,name=apk_path,json=apkPath,proto3" json:"apk_path,omitempty"`                               // /data/app/com.zhiliaoapp.musically-.../base.apk
	Field48           int64                  `protobuf:"varint,48,opt,name=field48,proto3" json:"field48,omitempty"`                                             // 56
	Sentinel_49       int64                  `protobuf:"varint,49,opt,name=sentinel_49,json=sentinel49,proto3" json:"sentinel_49,omitempty"`                     // 1999997
	Slot_50           string                 `protobuf:"bytes,50,opt,name=slot_50,json=slot50,proto3" json:"slot_50,omitempty"`                                  // "!notset!"
	Sentinel_51       int64                  `protobuf:"varint,51,opt,name=sentinel_51,json=sentinel51,proto3" json:"sentinel_51,omitempty"`                     // 1999997
	Sentinel_52       int64                  `protobuf:"varint,52,opt,name=sentinel_52,json=sentinel52,proto3" json:"sentinel_52,omitempty"`                     // 1999997
	Slot_53           string                 `protobuf:"bytes,53,opt,name=slot_53,json=slot53,proto3" json:"slot_53,omitempty"`                                  // "!notset!"
	Slot_54           string                 `protobuf:"bytes,54,opt,name=slot_54,json=slot54,proto3" json:"slot_54,omitempty"`                                  // "!notset!"
	Slot_55           string                 `protobuf:"bytes,55,opt,name=slot_55,json=slot55,proto3" json:"slot_55,omitempty"`                                  // "!notset!"
	Sentinel_56       int64                  `protobuf:"varint,56,opt,name=sentinel_56,json=sentinel56,proto3" json:"sentinel_56,omitempty"`                     // 1999997
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_internal_parser_tiktok_crypto_ttdevice_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_tiktok_crypto_ttdevice_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceBrand() string {
	if x != nil {
		return x.DeviceBrand
	}
	return ""
}

func (x *DeviceInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *DeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *DeviceInfo) GetScreenResolution() string {
	if x != nil {
		return x.ScreenResolution
	}
	return ""
}

func (x *DeviceInfo) GetScreenDpi() int64 {
	if x != nil {
		return x.ScreenDpi
	}
	return 0
}

func (x *DeviceInfo) GetRomBuildId() string {
	if x != nil {
		return x.RomBuildId
	}
	return ""
}

func (x *DeviceInfo) GetField10() int64 {
	if x != nil {
		return x.Field10
	}
	return 0
}

func (x *DeviceInfo) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *DeviceInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *DeviceInfo) GetTzOffset() int64 {
	if x != nil {
		return x.TzOffset
	}
	return 0
}

func (x *DeviceInfo) GetField14() int64 {
	if x != nil {
		return x.Field14
	}
	return 0
}

func (x *DeviceInfo) GetMemTotalBytes() int64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *DeviceInfo) GetStorageTotalA() int64 {
	if x != nil {
		return x.StorageTotalA
	}
	return 0
}

func (x *DeviceInfo) GetStorageTotalB() int64 {
	if x != nil {
		return x.StorageTotalB
	}
	return 0
}

func (x *DeviceInfo) GetStorageFree() int64 {
	if x != nil {
		return x.StorageFree
	}
	return 0
}

func (x *DeviceInfo) GetIdSlot_19() string {
	if x != nil {
		return x.IdSlot_19
	}
	return ""
}

func (x *DeviceInfo) GetIdSlot_20() string {
	if x != nil {
		return x.IdSlot_20
	}
	return ""
}

func (x *DeviceInfo) GetIdSlot_21() string {
	if x != nil {
		return x.IdSlot_21
	}
	return ""
}

func (x *DeviceInfo) GetIdSlot_22() string {
	if x != nil {
		return x.IdSlot_22
	}
	return ""
}

func (x *DeviceInfo) GetIdSlot_23() string {
	if x != nil {
		return x.IdSlot_23
	}
	return ""
}

func (x *DeviceInfo) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *DeviceInfo) GetTimestampA() int64 {
	if x != nil {
		return x.TimestampA
	}
	return 0
}

func (x *DeviceInfo) GetInstallUuid() string {
	if x != nil {
		return x.InstallUuid
	}
	return ""
}

func (x *DeviceInfo) GetDiskCapacity() int64 {
	if x != nil {
		return x.DiskCapacity
	}
	return 0
}

func (x *DeviceInfo) GetField28() string {
	if x != nil {
		return x.Field28
	}
	return ""
}

func (x *DeviceInfo) GetSentinel_29() int64 {
	if x != nil {
		return x.Sentinel_29
	}
	return 0
}

func (x *DeviceInfo) GetSentinel_30() int64 {
	if x != nil {
		return x.Sentinel_30
	}
	return 0
}

func (x *DeviceInfo) GetSlot_31() string {
	if x != nil {
		return x.Slot_31
	}
	return ""
}

func (x *DeviceInfo) GetSlot_32() string {
	if x != nil {
		return x.Slot_32
	}
	return ""
}

func (x *DeviceInfo) GetSlot_33() string {
	if x != nil {
		return x.Slot_33
	}
	return ""
}

func (x *DeviceInfo) GetSlot_34() string {
	if x != nil {
		return x.Slot_34
	}
	return ""
}

func (x *DeviceInfo) GetSlot_35() string {
	if x != nil {
		return x.Slot_35
	}
	return ""
}

func (x *DeviceInfo) GetSentinel_36() int64 {
	if x != nil {
		return x.Sentinel_36
	}
	return 0
}

func (x *DeviceInfo) GetSentinel_37() int64 {
	if x != nil {
		return x.Sentinel_37
	}
	return 0
}

func (x *DeviceInfo) GetSlot_38() string {
	if x != nil {
		return x.Slot_38
	}
	return ""
}

func (x *DeviceInfo) GetSlot_39() string {
	if x != nil {
		return x.Slot_39
	}
	return ""
}

func (x *DeviceInfo) GetNetIpList() string {
	if x != nil {
		return x.NetIpList
	}
	return ""
}

func (x *DeviceInfo) GetSentinel_41() int64 {
	if x != nil {
		return x.Sentinel_41
	}
	return 0
}

func (x *DeviceInfo) GetSentinel_42() int64 {
	if x != nil {
		return x.Sentinel_42
	}
	return 0
}

func (x *DeviceInfo) GetSlot_44() string {
	if x != nil {
		return x.Slot_44
	}
	return ""
}

func (x *DeviceInfo) GetField45() int64 {
	if x != nil {
		return x.Field45
	}
	return 0
}

func (x *DeviceInfo) GetTimestampB() int64 {
	if x != nil {
		return x.TimestampB
	}
	return 0
}

func (x *DeviceInfo) GetApkPath() string {
	if x != nil {
		return x.ApkPath
	}
	return ""
}

func (x *DeviceInfo) GetField48() int64 {
	if x != nil {
		return x.Field48
	}
	return 0
}

func (x *DeviceInfo) GetSentinel_49() int64 {
	if x != nil {
		return x.Sentinel_49
	}
	return 0
}

func (x *DeviceInfo) GetSlot_50() string {
	if x != nil {
		return x.Slot_50
	}
	return ""
}

func (x *DeviceInfo) GetSentinel_51() int64 {
	if x != nil {
		return x.Sentinel_51
	}
	return 0
}

func (x *DeviceInfo) GetSentinel_52() int64 {
	if x != nil {
		return x.Sentinel_52
	}
	return 0
}

func (x *DeviceInfo) GetSlot_53() string {
	if x != nil {
		return x.Slot_53
	}
	return ""
}

func (x *DeviceInfo) GetSlot_54() string {
	if x != nil {
		return x.Slot_54
	}
	return ""
}

func (x *DeviceInfo) GetSlot_55() string {
	if x != nil {
		return x.Slot_55
	}
	return ""
}

func (x *DeviceInfo) GetSentinel_56() int64 {
	if x != nil {
		return x.Sentinel_56
	}
	return 0
}

var File_internal_parser_tiktok_crypto_ttdevice_device_proto protoreflect.FileDescriptor

const file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDesc = "" +
	"\n" +
	"3internal/parser/tiktok/crypto/ttdevice/device.proto\x12\bttdevice\"\xab\r\n" +
	"\n" +
	"DeviceInfo\x12!\n" +
	"\fdevice_brand\x18\x01 \x01(\tR\vdeviceBrand\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12!\n" +
	"\fdevice_model\x18\x03 \x01(\tR\vdeviceModel\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\aos_name\x18\x05 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tR\tosVersion\x12+\n" +
	"\x11screen_resolution\x18\a \x01(\tR\x10screenResolution\x12\x1d\n" +
	"\n" +
	"screen_dpi\x18\b \x01(\x03R\tscreenDpi\x12 \n" +
	"\from_build_id\x18\t \x01(\tR\n" +
	"romBuildId\x12\x18\n" +
	"\afield10\x18\n" +
	" \x01(\x03R\afield10\x12\x16\n" +
	"\x06locale\x18\v \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x12\x1b\n" +
	"\ttz_offset\x18\r \x01(\x03R\btzOffset\x12\x18\n" +
	"\afield14\x18\x0e \x01(\x03R\afield14\x12&\n" +
	"\x0fmem_total_bytes\x18\x0f \x01(\x03R\rmemTotalBytes\x12&\n" +
	"\x0fstorage_total_a\x18\x10 \x01(\x03R\rstorageTotalA\x12&\n" +
	"\x0fstorage_total_b\x18\x11 \x01(\x03R\rstorageTotalB\x12!\n" +
	"\fstorage_free\x18\x12 \x01(\x03R\vstorageFree\x12\x1c\n" +
	"\n" +
	"id_slot_19\x18\x13 \x01(\tR\bidSlot19\x12\x1c\n" +
	"\n" +
	"id_slot_20\x18\x14 \x01(\tR\bidSlot20\x12\x1c\n" +
	"\n" +
	"id_slot_21\x18\x15 \x01(\tR\bidSlot21\x12\x1c\n" +
	"\n" +
	"id_slot_22\x18\x16 \x01(\tR\bidSlot22\x12\x1c\n" +
	"\n" +
	"id_slot_23\x18\x17 \x01(\tR\bidSlot23\x12-\n" +
	"\x12device_fingerprint\x18\x18 \x01(\tR\x11deviceFingerprint\x12\x1f\n" +
	"\vtimestamp_a\x18\x19 \x01(\x03R\n" +
	"timestampA\x12!\n" +
	"\finstall_uuid\x18\x1a \x01(\tR\vinstallUuid\x12#\n" +
	"\rdisk_capacity\x18\x1b \x01(\x03R\fdiskCapacity\x12\x18\n" +
	"\afield28\x18\x1c \x01(\tR\afield28\x12\x1f\n" +
	"\vsentinel_29\x18\x1d \x01(\x03R\n" +
	"sentinel29\x12\x1f\n" +
	"\vsentinel_30\x18\x1e \x01(\x03R\n" +
	"sentinel30\x12\x17\n" +
	"\aslot_31\x18\x1f \x01(\tR\x06slot31\x12\x17\n" +
	"\aslot_32\x18  \x01(\tR\x06slot32\x12\x17\n" +
	"\aslot_33\x18! \x01(\tR\x06slot33\x12\x17\n" +
	"\aslot_34\x18\" \x01(\tR\x06slot34\x12\x17\n" +
	"\aslot_35\x18# \x01(\tR\x06slot35\x12\x1f\n" +
	"\vsentinel_36\x18$ \x01(\x03R\n" +
	"sentinel36\x12\x1f\n" +
	"\vsentinel_37\x18% \x01(\x03R\n" +
	"sentinel37\x12\x17\n" +
	"\aslot_38\x18& \x01(\tR\x06slot38\x12\x17\n" +
	"\aslot_39\x18' \x01(\tR\x06slot39\x12\x1e\n" +
	"\vnet_ip_list\x18( \x01(\tR\tnetIpList\x12\x1f\n" +
	"\vsentinel_41\x18) \x01(\x03R\n" +
	"sentinel41\x12\x1f\n" +
	"\vsentinel_42\x18* \x01(\x03R\n" +
	"sentinel42\x12\x17\n" +
	"\aslot_44\x18, \x01(\tR\x06slot44\x12\x18\n" +
	"\afield45\x18- \x01(\x03R\afield45\x12\x1f\n" +
	"\vtimestamp_b\x18. \x01(\x03R\n" +
	"timestampB\x12\x19\n" +
	"\bapk_path\x18/ \x01(\tR\aapkPath\x12\x18\n" +
	"\afield48\x180 \x01(\x03R\afield48\x12\x1f\n" +
	"\vsentinel_49\x181 \x01(\x03R\n" +
	"sentinel49\x12\x17\n" +
	"\aslot_50\x182 \x01(\tR\x06slot50\x12\x1f\n" +
	"\vsentinel_51\x183 \x01(\x03R\n" +
	"sentinel51\x12\x1f\n" +
	"\vsentinel_52\x184 \x01(\x03R\n" +
	"sentinel52\x12\x17\n" +
	"\aslot_53\x185 \x01(\tR\x06slot53\x12\x17\n" +
	"\aslot_54\x186 \x01(\tR\x06slot54\x12\x17\n" +
	"\aslot_55\x187 \x01(\tR\x06slot55\x12\x1f\n" +
	"\vsentinel_56\x188 \x01(\x03R\n" +
	"sentinel56B?Z=tiktokdownload/backend/internal/parser/tiktok/crypto/ttdeviceb\x06proto3"

var (
	file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescOnce sync.Once
	file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescData []byte
)

func file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescGZIP() []byte {
	file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescOnce.Do(func() {
		file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDesc), len(file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDesc)))
	})
	return file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDescData
}

var file_internal_parser_tiktok_crypto_ttdevice_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_parser_tiktok_crypto_ttdevice_device_proto_goTypes = []any{
	(*DeviceInfo)(nil), // 0: ttdevice.DeviceInfo
}
var file_internal_parser_tiktok_crypto_ttdevice_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_parser_tiktok_crypto_ttdevice_device_proto_init() }
func file_internal_parser_tiktok_crypto_ttdevice_device_proto_init() {
	if File_internal_parser_tiktok_crypto_ttdevice_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDesc), len(file_internal_parser_tiktok_crypto_ttdevice_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_parser_tiktok_crypto_ttdevice_device_proto_goTypes,
		DependencyIndexes: file_internal_parser_tiktok_crypto_ttdevice_device_proto_depIdxs,
		MessageInfos:      file_internal_parser_tiktok_crypto_ttdevice_device_proto_msgTypes,
	}.Build()
	File_internal_parser_tiktok_crypto_ttdevice_device_proto = out.File
	file_internal_parser_tiktok_crypto_ttdevice_device_proto_goTypes = nil
	file_internal_parser_tiktok_crypto_ttdevice_device_proto_depIdxs = nil
}
